version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    reviewers:
      - "maintainers"
    assignees:
      - "security-team"
    labels:
      - "dependencies"
      - "automated"
      - "security"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "develop"
    vendor: true
    versioning-strategy: "increase"
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-tuesday"
      time: "06:00"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "documentation"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]