# Hadolint configuration for Docker best practices
# https://github.com/hadolint/hadolint

# Ignore specific rules
ignored:
  - DL3008  # Pin versions in apt-get install
  - DL3009  # Delete the apt-get lists after installing
  - DL3015  # Avoid additional packages by specifying --no-install-recommends
  - DL3018  # Pin versions in apk add
  - DL3019  # Use the --no-cache switch
  - SC2046  # Quote this to prevent word splitting
  - SC2086  # Double quote to prevent globbing and word splitting

# Trusted registries for base images
trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
  - registry.hub.docker.com
  - python
  - ubuntu
  - alpine
  - debian

# Override specific rules
override:
  error:
    - DL3020  # Use COPY instead of ADD for files
    - DL3025  # Use arguments JSON notation for CMD and ENTRYPOINT
  warning:
    - DL3007  # Using latest tag
    - DL3006  # Always tag the version of an image explicitly
  info:
    - DL3032  # yum clean all missing
  style:
    - DL3033  # Specify version with yum install

# Format configuration
format: tty
noColor: false
noFail: false

# Failure threshold
failureThreshold: error

# Inline ignore patterns
inlineIgnoreEnabled: true

# Shell used for RUN instructions
shell: ["/bin/bash", "-o", "pipefail", "-c"]