name: 🚀 Performance Optimization Request
description: Request performance improvements for privacy-preserving training
title: "[PERF] "
labels: ["performance", "optimization", "enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## Performance Optimization Request
        
        Help us improve the performance of privacy-preserving training while maintaining privacy guarantees.

  - type: dropdown
    id: performance_area
    attributes:
      label: Performance Area
      description: Which area needs performance optimization?
      options:
        - Training Speed - DP-SGD training optimization
        - Memory Usage - Reduce memory consumption
        - Privacy Overhead - Minimize privacy computation cost
        - Model Inference - Faster private inference
        - Data Loading - Dataset preprocessing optimization
        - GPU Utilization - Better hardware utilization
        - Federated Learning - Distributed training efficiency
        - Context Protection - Faster PII redaction
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How critical is this performance optimization?
      options:
        - Critical - Blocking production use
        - High - Significant impact on user experience
        - Medium - Noticeable improvement needed
        - Low - Nice-to-have optimization
    validations:
      required: true

  - type: textarea
    id: current_performance
    attributes:
      label: Current Performance Metrics
      description: What are the current performance characteristics?
      placeholder: |
        Current metrics:
        - Training speed: X tokens/second
        - Memory usage: X GB
        - Privacy overhead: X% slower than non-private
        - Model size: X parameters
        - Hardware: GPU/CPU specifications
    validations:
      required: true

  - type: textarea
    id: target_performance
    attributes:
      label: Target Performance Goals
      description: What performance targets would you like to achieve?
      placeholder: |
        Target improvements:
        - Training speed: X% faster
        - Memory usage: X% reduction
        - Privacy overhead: X% reduction
        - Throughput: X requests/second
    validations:
      required: true