name: Security Vulnerability
description: Report a security vulnerability (use this for security issues only)
title: "[SECURITY] "
labels: ["security", "vulnerability", "critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🔒 Security Vulnerability Report
        
        **IMPORTANT: For critical security vulnerabilities, please email security@terragon-labs.com instead of creating a public issue.**
        
        Use this template only for non-critical security improvements or if directed by our security team.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security vulnerability?
      options:
        - Critical - Immediate security risk requiring urgent action
        - High - Significant security risk
        - Medium - Moderate security risk
        - Low - Minor security improvement
        - Info - Security-related information or documentation
    validations:
      required: true

  - type: dropdown
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - Code Injection - SQL, Command, etc.
        - Authentication/Authorization - Access control issues
        - Cryptographic - Weak encryption, key management
        - Input Validation - Unsafe input handling
        - Dependency - Vulnerable third-party libraries
        - Configuration - Insecure default settings
        - Information Disclosure - Unintended data exposure
        - Model Security - ML-specific attacks
        - Infrastructure - Container, network security
        - Supply Chain - Build/deployment security
        - Other
    validations:
      required: true

  - type: textarea
    id: vulnerability_description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the security vulnerability
      placeholder: |
        Please describe:
        1. What the vulnerability is
        2. Where it exists in the codebase
        3. How it could be exploited
        4. Potential impact
        
        **DO NOT include actual exploit code or sensitive details in public issues**
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce (General)
      description: General steps to identify this vulnerability (no exploit details)
      placeholder: |
        1. Navigate to...
        2. Configure...
        3. Observe...
        
        **Keep this general - do not include specific exploit steps**
    validations:
      required: false

  - type: textarea
    id: impact_assessment
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Data that could be compromised
        - Systems that could be affected  
        - Business impact
        - User impact
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Affected Environment
      description: Which environments are affected?
      multiple: true
      options:
        - Development
        - Testing
        - Staging
        - Production
        - All Environments
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Affected Version(s)
      description: What version(s) are affected?
      placeholder: v0.1.0, v0.2.0, etc.
    validations:
      required: true

  - type: textarea
    id: suggested_fix
    attributes:
      label: Suggested Fix
      description: Do you have suggestions for how to fix this vulnerability?
      placeholder: |
        General recommendations for addressing this vulnerability...
        - Update dependencies
        - Implement input validation
        - Use secure defaults
        - etc.
    validations:
      required: false

  - type: checkboxes
    id: security_checklist
    attributes:
      label: Security Reporting Checklist
      description: Please confirm you've followed security reporting guidelines
      options:
        - label: I have not included exploit code or sensitive details in this public issue
          required: true
        - label: I understand this will be handled as a security issue with appropriate priority
          required: true
        - label: I have checked if this is already a known security issue
          required: true
        - label: For critical vulnerabilities, I have used private reporting channels instead
          required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about this security vulnerability
      placeholder: Add any other context about the vulnerability here.
    validations:
      required: false