apiVersion: v1
kind: Namespace
metadata:
  name: privacy-finetuner
  labels:
    name: privacy-finetuner
    purpose: distributed-training
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: privacy-finetuner-quota
  namespace: privacy-finetuner
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 500Gi
    requests.nvidia.com/gpu: "20"
    limits.cpu: "200"
    limits.memory: 1000Gi
    limits.nvidia.com/gpu: "20"
    persistentvolumeclaims: "10"
    services: "20"
    count/deployments.apps: "10"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: privacy-finetuner-network-policy
  namespace: privacy-finetuner
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: privacy-finetuner
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8090
    - protocol: TCP
      port: 9090
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
  - to:
    - namespaceSelector:
        matchLabels:
          name: privacy-finetuner
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80