apiVersion: v1
kind: ServiceAccount
metadata:
  name: privacy-finetuner-service-account
  namespace: privacy-finetuner
  labels:
    app: privacy-finetuner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privacy-finetuner-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers", "verticalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["custom.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["external.metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames: ["privacy-finetuner-psp"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: privacy-finetuner
  name: privacy-finetuner-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privacy-finetuner-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: privacy-finetuner-service-account
  namespace: privacy-finetuner
roleRef:
  kind: ClusterRole
  name: privacy-finetuner-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privacy-finetuner-role-binding
  namespace: privacy-finetuner
subjects:
- kind: ServiceAccount
  name: privacy-finetuner-service-account
  namespace: privacy-finetuner
roleRef:
  kind: Role
  name: privacy-finetuner-role
  apiGroup: rbac.authorization.k8s.io