{{- if .Values.master.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "privacy-finetuner.fullname" . }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-finetuner.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  replicas: {{ .Values.master.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "privacy-finetuner.masterSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "privacy-finetuner.masterSelectorLabels" . | nindent 8 }}
        {{- with .Values.master.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.metrics.port }}"
        prometheus.io/path: "/metrics"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.master.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "privacy-finetuner.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "privacy-finetuner.serviceAccountName" . }}
      
      {{- include "privacy-finetuner.nodeSelector" .Values.master | nindent 6 }}
      {{- include "privacy-finetuner.tolerations" .Values.master | nindent 6 }}
      {{- include "privacy-finetuner.affinity" .Values.master | nindent 6 }}
      
      securityContext:
        {{- toYaml .Values.master.securityContext | nindent 8 }}
      
      initContainers:
      - name: setup-permissions
        image: busybox:1.35
        securityContext:
          runAsUser: 0
        command:
        - sh
        - -c
        - |
          chown -R 1000:1000 /data /models /cache /var/log/privacy-finetuner
          chmod -R 755 /data /models /cache /var/log/privacy-finetuner
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: models-volume
          mountPath: /models
        - name: cache-volume
          mountPath: /cache
        - name: logs-volume
          mountPath: /var/log/privacy-finetuner
      
      containers:
      - name: privacy-finetuner
        image: {{ include "privacy-finetuner.masterImage" . }}
        imagePullPolicy: {{ .Values.master.image.pullPolicy }}
        
        securityContext:
          {{- toYaml .Values.master.containerSecurityContext | nindent 10 }}
        
        {{- include "privacy-finetuner.resources" .Values.master | nindent 8 }}
        
        env:
        {{- include "privacy-finetuner.commonEnv" . | nindent 8 }}
        - name: RANK
          value: "0"
        - name: WORLD_SIZE
          value: {{ add .Values.master.replicaCount .Values.workers.replicaCount | quote }}
        - name: NODE_RANK
          value: "0"
        - name: LOCAL_RANK
          value: "0"
        {{- range $key, $value := .Values.master.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        
        envFrom:
        - secretRef:
            name: {{ include "privacy-finetuner.fullname" . }}-secrets
        - configMapRef:
            name: {{ include "privacy-finetuner.fullname" . }}-config
        
        ports:
        - name: http
          containerPort: {{ .Values.service.master.port }}
          protocol: TCP
        - name: metrics
          containerPort: {{ .Values.service.metrics.port }}
          protocol: TCP
        - name: distributed
          containerPort: 29500
          protocol: TCP
        - name: distributed-tcp
          containerPort: 29501
          protocol: TCP
        
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: data-volume
          mountPath: /data
        - name: models-volume
          mountPath: /models
        - name: cache-volume
          mountPath: /cache
        - name: logs-volume
          mountPath: /var/log/privacy-finetuner
        - name: tmp-volume
          mountPath: /tmp
        - name: dev-shm
          mountPath: /dev/shm
        
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                echo "Gracefully shutting down privacy-finetuner master..."
                kill -TERM $(pgrep -f privacy-finetuner)
                sleep 30
      
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "privacy-finetuner.fullname" . }}-config
      {{- if .Values.persistence.data.enabled }}
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "privacy-finetuner.fullname" . }}-data
      {{- else }}
      - name: data-volume
        emptyDir: {}
      {{- end }}
      {{- if .Values.persistence.models.enabled }}
      - name: models-volume
        persistentVolumeClaim:
          claimName: {{ include "privacy-finetuner.fullname" . }}-models
      {{- else }}
      - name: models-volume
        emptyDir: {}
      {{- end }}
      {{- if .Values.persistence.cache.enabled }}
      - name: cache-volume
        persistentVolumeClaim:
          claimName: {{ include "privacy-finetuner.fullname" . }}-cache
      {{- else }}
      - name: cache-volume
        emptyDir: {}
      {{- end }}
      - name: logs-volume
        emptyDir:
          sizeLimit: 10Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 5Gi
      - name: dev-shm
        emptyDir:
          medium: Memory
          sizeLimit: 8Gi
      
      terminationGracePeriodSeconds: 300
      restartPolicy: Always
{{- end }}