{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "privacy-finetuner.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-finetuner.labels" . | nindent 4 }}
    type: data
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  {{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}

---

{{- if .Values.persistence.models.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "privacy-finetuner.fullname" . }}-models
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-finetuner.labels" . | nindent 4 }}
    type: models
  {{- with .Values.persistence.models.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.models.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
  {{- if .Values.persistence.models.storageClass }}
  {{- if (eq "-" .Values.persistence.models.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.models.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}

---

{{- if .Values.persistence.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "privacy-finetuner.fullname" . }}-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-finetuner.labels" . | nindent 4 }}
    type: cache
  {{- with .Values.persistence.cache.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.cache.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
  {{- if .Values.persistence.cache.storageClass }}
  {{- if (eq "-" .Values.persistence.cache.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.cache.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}