apiVersion: v1
kind: Secret
metadata:
  name: {{ include "privacy-finetuner.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-finetuner.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.database.password | b64enc }}
  DB_USERNAME: {{ .Values.secrets.database.username | b64enc }}
  API_SECRET_KEY: {{ .Values.secrets.apiSecretKey }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  MODEL_REGISTRY_TOKEN: {{ .Values.secrets.modelRegistryToken }}
  PRIVACY_ENCRYPTION_KEY: {{ .Values.secrets.privacyEncryptionKey }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3.accessKey }}
  S3_SECRET_KEY: {{ .Values.secrets.s3.secretKey }}

---

{{- if .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "privacy-finetuner.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-finetuner.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if and .Values.secrets.tls.crt .Values.secrets.tls.key }}
  tls.crt: {{ .Values.secrets.tls.crt }}
  tls.key: {{ .Values.secrets.tls.key }}
  {{- else }}
  {{- include "privacy-finetuner.gen-certs" . | nindent 2 }}
  {{- end }}
{{- end }}

---

{{- if .Values.secrets.dockerRegistry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "privacy-finetuner.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privacy-finetuner.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.registry .Values.secrets.dockerRegistry.username .Values.secrets.dockerRegistry.password (printf "%s:%s" .Values.secrets.dockerRegistry.username .Values.secrets.dockerRegistry.password | b64enc) | b64enc }}
{{- end }}